services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TOKENIZER=dkleczek/bert-base-polish-cased-v1
      - CHUNK_SIZE=100
      - DB=marqo
      - MARQO_URL=http://marqo:8882
      - MARQO_INDEX_NAME=wikipedia
      - MARQO_MODEL=hf/multilingual-e5-base
      - MAX_CHARS=1000
      - MAX_RECORDS=10

  marqo:
    image: marqoai/marqo:latest
