services:
  api:
    image: qaziok/iis-api:main
    ports:
      - "8080:8080"
    environment:
      - TOKENIZER=dkleczek/bert-base-polish-cased-v1
      - CHUNK_SIZE=100
      - DB=marqo
      - MARQO_URL=http://marqo:8882
      - MARQO_INDEX_NAME=wikipedia
      - MARQO_MODEL=hf/multilingual-e5-base
      - MAX_CHARS=1000
      - MAX_RECORDS=10
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  web:
    image: qaziok/iis-web
    ports:
      - "80:80"
    environment:
      - VUE_APP_API_URL=/api
      - VUE_APP_API_TIMEOUT=10000

  marqo:
    image: marqoai/marqo:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
