services:
  api:
    image: qaziok/iis-api:main
    ports:
      - "8080:8080"
    environment:
      - TOKENIZER=dkleczek/bert-base-polish-cased-v1
      - CHUNK_SIZE=100
      - INDEX_NAME=wikipedia
      - MAX_CHARS=1000
      - MAX_RECORDS=100
      - INCLUDE_TESTS=true
    env_file: # change this env file to change used database
      - .env.chroma
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  web:
    image: qaziok/iis-web
    ports:
      - "80:80"
    environment:
      - VUE_APP_API_URL=/api
      - VUE_APP_API_TIMEOUT=10000

  marqo:
    image: marqoai/marqo:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  chroma:
    image: chromadb/chroma
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
