services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TOKENIZER=dkleczek/bert-base-polish-cased-v1
      - CHUNK_SIZE=100
      - DB=marqo
      - INDEX_NAME=wikipedia
      - MARQO_URL=http://marqo:8882
      - MARQO_MODEL=hf/multilingual-e5-base
      - MAX_CHARS=1000
      - MAX_RECORDS=100
      - INCLUDE_TESTS=true
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - CHROMA_MODEL=intfloat/multilingual-e5-base
      - CHROMA_DEVICE=cpu

  marqo:
    image: marqoai/marqo:latest

  chroma:
    image: chromadb/chroma:latest
