services:
  chroma:
    image: chromadb/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=${PERSIST_DIRECTORY:-/chroma/chroma}
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-..}/volumes/chroma:/chroma/chroma
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  api:
    image: qaziok/iis-api:main
    ports:
      - "18434:8080"
    env_file:
      - .env.chroma
    depends_on:
      - "chroma"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
              
  web:
    image: qaziok/iis-web
    ports:
      - "18435:80"
    environment:
      - VUE_APP_API_URL=/api
      - VUE_APP_API_TIMEOUT=10000
    depends_on:
      - "api"